// <auto-generated />
using System;
using KapasitematikBlog.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KapasitematikBlog.Migrations
{
    [DbContext(typeof(KapasitematikBlogDbContext))]
    [Migration("20220217145126_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KapasitematikBlog.Domain.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminAd")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("AdminRole")
                        .HasMaxLength(1);

                    b.Property<string>("AdminSifre")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("AdminId");

                    b.ToTable("ADMIN");
                });

            modelBuilder.Entity("KapasitematikBlog.Domain.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAd")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("KategoriId");

                    b.ToTable("KATEGORI");
                });

            modelBuilder.Entity("KapasitematikBlog.Domain.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAd")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KullaniciName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KullaniciPassword")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KullaniciSoyad")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("KullaniciId");

                    b.ToTable("KULLANICI");
                });

            modelBuilder.Entity("KapasitematikBlog.Domain.Makale", b =>
                {
                    b.Property<int>("MakaleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MakaleAciklama");

                    b.Property<string>("MakaleBaslik")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("MakaleKategoriId");

                    b.Property<string>("ResimUrl");

                    b.HasKey("MakaleId");

                    b.HasIndex("MakaleKategoriId");

                    b.ToTable("MAKALE");
                });

            modelBuilder.Entity("KapasitematikBlog.Domain.Resim", b =>
                {
                    b.Property<int>("ResimId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResimUrl")
                        .HasColumnName("Resim");

                    b.HasKey("ResimId");

                    b.ToTable("RESIM");
                });

            modelBuilder.Entity("KapasitematikBlog.Domain.Makale", b =>
                {
                    b.HasOne("KapasitematikBlog.Domain.Kategori", "MakaleKategori")
                        .WithMany("Makale")
                        .HasForeignKey("MakaleKategoriId")
                        .HasConstraintName("FK_MAKALE_KATEGORI1");
                });
#pragma warning restore 612, 618
        }
    }
}
